---
version: "3.7"

services:
  # Homeassistant https://www.home-assistant.io/installation/raspberrypi
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - nfs_mount:/config  # Mount the NFS share directly
      # - /home/pi/homelab/pi5/homeassistant_config/:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # Essential to make bluetooth work
    #ports:
    #      - "8123:8123"
    #      - "8300:8300"
    #      - "51827:51827"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: host
    cap_add: #Essential for bluetooth
      - NET_ADMIN
      - NET_RAW

volumes:
  nfs_mount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.39,rw
      device: ":/mnt/tank/set1/homeassistant_config"
